# network profiles
systemd_networkd_network:
  eth0:
    - Match:
      - Name: "eth0"
      - MACAddress: "{{ ansible_default_ipv6.macaddress }}"
    - Network:
      - DHCP: "ipv6"
      - LinkLocalAddressing: "ipv6"
      - IPv6AcceptRouterAdvertisements: "no"

      - Address: "{{ ansible_default_ipv6.address }}/{{ ansible_default_ipv6.prefix }}"
      - Gateway: "{{ ansible_default_ipv6.gateway }}"
      - DNS: "2a02:c205::1:53"
      - DNS: "2a02:c205::2:53"

    - Route:
      - Destination: "::/0"
      - Gateway: "{{ ansible_default_ipv6.gateway }}"
      - IPv6Preference: "high"

    - DHCP:
      - RouteMetric: 100
      - UseMTU: "false"

# link profiles
systemd_networkd_link:
  eth0:
    - Match:
      - MACAddress: "{{ ansible_default_ipv6.macaddress }}"
    - Link:
      - Name: "eth0"
      - WakeOnLan: "off"
      - MTUBytes: 1500


# netdev profiles
systemd_networkd_netdev: []

# does the role have to restart systemd-networkd to apply the new profiles ?
systemd_networkd_apply_config: false

# We're using a runtime contfiguration from netplan provided by cloud-init,
# so just enforce systemd-networkd to be running.
# Above config is therefore just a backup, as it's overwritten by runtime.
