timesync_timezone: Europe/Berlin
timesync_ntp_hosts:
  - 0.europe.pool.ntp.org
  - 1.europe.pool.ntp.org
  - 2.europe.pool.ntp.org
  - 3.europe.pool.ntp.org
timesync_fallback_ntp_hosts:
  - ntp1.ipv6.teleport-iabg.de
  - ntp2.ipv6.teleport-iabg.de
  - ntp1.ipv6.lrz-muenchen.de
